name: 'actions-semver'
description: 'Github actions for Sem-ver'
author: 'd-share <dev@dshare.co.kr>'
branding:
  icon: 'check'
  color: 'white'
inputs:
  version:
    required: false
    description: 'Base version'
  method:
    required: true
    description: 'Action(Bump) method - major, minor, patch, beta, alpha, default.'
  return_with_prefix:
    required: false
    default: 'true'
    description: 'Set output with prefixed version tag'
  return_with_suffix:
    required: false
    default: 'true'
    description: 'Set output with suffixed version tag'

outputs:
  original_version:
    description: 'Original version'
  version:
    description: 'Modified (Bump) Version'
  prefix:
    description: 'Prefix'
  suffix:
    description: 'Suffix'

runs:
  using: 'node12'
  main: 'dist/index.js'

